// 4.1.1	Simple filtering
fWindowsEvent
| where Channel =='Security'
| where EventID == 4688

// 4.1.2	Using different predicates with ‘where’
fWindowsEvent
| where Channel =='Security'
| where EventID == 4624
| where EventData.TargetUserName=='PBEESLY'

// 4.1.3	Using lookups with ‘where’
let start_time = ago(14d); 
fWindowsEvent
| where TimeGenerated > start_time 
| where Channel =='Security'
| where EventID == 5145
